name: 'Update Submodule'
description: 'Update repository submodule'

inputs:
  path:
    description: 'Submodule path'
    required: true

runs:
  using: "composite"
  steps:
    - name: Update Submodule
      run: git submodule update --remote ${{ inputs.path }}
      shell: bash
    - name: Commit Update
      run: |
        git config user.email "actions@github.com"
        git config user.name "GHAction - Update Submodule"
        git add --all
        git commit -m "Update submodule" -m "${{ inputs.path }}" || echo "No changes to commit"
      shell: bash